### ISSUE TITLE
新版的1.16.1有做么？

### ISSUE THREAD

**Issue by wdjwxh** [brian9206/fgo-biligame-bot#1]
我在改成ios的过程中发现rgusk到usk的算法好像变了...

**Comment by wdjwxh** [comment]
或者说KEY改了..

**Comment by brian9206** [comment]
舊版本的funny key我是在apk包中某一個native dll (或.so, 總之是一個native binary中)檔dump出來的
這個binary只有一個function, 就是return這個funny key (B站的程序員是以為native code別人就找不到嗎)
1.17.1似乎已經加密了, 我只找到unity用的managed dll
如果是這樣的話, 估計可以在運行中的遊戲內存中找到funny key..

**Comment by brian9206** [comment]
da76f47 resolved this issue.
